import { Avatar, DiceType, PlayerData, PlayerType, Team } from '../interfaces/player-data';

export const MOCK_PLAYER_IDS = ['3333', '4444', '5555', '6666'];

export const MOCK_PLAYER_DATAS: PlayerData[] = [
    {
        id: structuredClone(MOCK_PLAYER_IDS[0]),
        name: 'Player1',
        avatar: Avatar.Avatar1,
        isConnected: true,
        spawnPoint: { x: 1, y: 1 },
        items: [],
        health: 4,
        speed: 6,
        attackDice: DiceType.D6,
        defenseDice: DiceType.D4,
        position: { x: 1, y: 1 },
        combatsWon: 0,
        type: PlayerType.Player,
        team: Team.None,
    },
    {
        id: structuredClone(MOCK_PLAYER_IDS[1]),
        name: 'Player2',
        avatar: Avatar.Avatar2,
        isConnected: true,
        spawnPoint: { x: 2, y: 2 },
        items: [],
        health: 4,
        speed: 6,
        attackDice: DiceType.D6,
        defenseDice: DiceType.D4,
        position: { x: 2, y: 2 },
        combatsWon: 0,
        type: PlayerType.Player,
        team: Team.None,
    },
    {
        id: structuredClone(MOCK_PLAYER_IDS[2]),
        name: 'Player1',
        avatar: Avatar.Avatar3,
        isConnected: true,
        spawnPoint: { x: 3, y: 3 },
        items: [],
        health: 4,
        speed: 6,
        attackDice: DiceType.D6,
        defenseDice: DiceType.D4,
        position: { x: 3, y: 3 },
        combatsWon: 0,
        type: PlayerType.Player,
        team: Team.None,
    },
    {
        id: structuredClone(MOCK_PLAYER_IDS[4]),
        name: 'Player1',
        avatar: Avatar.Avatar1,
        isConnected: true,
        spawnPoint: { x: 4, y: 4 },
        items: [],
        health: 4,
        speed: 6,
        attackDice: DiceType.D6,
        defenseDice: DiceType.D4,
        position: { x: 4, y: 4 },
        combatsWon: 0,
        type: PlayerType.Player,
        team: Team.None,
    },
];
