import { Avatar } from '../interfaces/player-data';

export const MIN_SELECTABLE_AVATAR_INDEX = 1;
export const MAX_SELECTABLE_AVATAR_INDEX = 13;

export const AVATAR_DATA = {
    [Avatar.Default]: {
        name: 'Default',
        image: './assets/images/game/avatars/default.png',
        imageFace: './assets/images/game/avatars/face/default.png',
        imageCentered: './assets/images/game/avatars/centered/default.png',
        frontGif: './assets/images/game/avatars-gifs/bulbasaur.gif',
        backGif: './assets/images/game/avatars-gifs/bulbasaur-back.gif',
    },
    [Avatar.Avatar1]: {
        name: 'Bulbizarre',
        image: './assets/images/game/avatars/bulbasaur.png',
        imageFace: './assets/images/game/avatars/face/bulbasaur.png',
        imageCentered: './assets/images/game/avatars/centered/bulbasaur.png',
        frontGif: './assets/images/game/avatars-gifs/bulbasaur.gif',
        backGif: './assets/images/game/avatars-gifs/bulbasaur-back.gif',
    },
    [Avatar.Avatar2]: {
        name: 'Carapuce',
        image: './assets/images/game/avatars/squirtle.png',
        imageFace: './assets/images/game/avatars/face/squirtle.png',
        imageCentered: './assets/images/game/avatars/centered/squirtle.png',
        frontGif: './assets/images/game/avatars-gifs/squirtle.gif',
        backGif: './assets/images/game/avatars-gifs/squirtle-back.gif',
    },
    [Avatar.Avatar3]: {
        name: 'Salamèche',
        image: './assets/images/game/avatars/charmander.png',
        imageFace: './assets/images/game/avatars/face/charmander.png',
        imageCentered: './assets/images/game/avatars/centered/charmander.png',
        frontGif: './assets/images/game/avatars-gifs/charmander.gif',
        backGif: './assets/images/game/avatars-gifs/charmander-back.gif',
    },
    [Avatar.Avatar4]: {
        name: 'Pikachu',
        image: './assets/images/game/avatars/pikachu.png',
        imageFace: './assets/images/game/avatars/face/pikachu.png',
        imageCentered: './assets/images/game/avatars/centered/pikachu.png',
        frontGif: './assets/images/game/avatars-gifs/pikachu.gif',
        backGif: './assets/images/game/avatars-gifs/pikachu-back.gif',
    },
    [Avatar.Avatar5]: {
        name: 'Rondoudou',
        image: './assets/images/game/avatars/jigglypuff.png',
        imageFace: './assets/images/game/avatars/face/jigglypuff.png',
        imageCentered: './assets/images/game/avatars/centered/jigglypuff.png',
        frontGif: './assets/images/game/avatars-gifs/jigglypuff.gif',
        backGif: './assets/images/game/avatars-gifs/jigglypuff-back.gif',
    },
    [Avatar.Avatar6]: {
        name: 'Psykokwak',
        image: './assets/images/game/avatars/psyduck.png',
        imageFace: './assets/images/game/avatars/face/psyduck.png',
        imageCentered: './assets/images/game/avatars/centered/psyduck.png',
        frontGif: './assets/images/game/avatars-gifs/psyduck.gif',
        backGif: './assets/images/game/avatars-gifs/psyduck-back.gif',
    },
    [Avatar.Avatar7]: {
        name: 'Goupix',
        image: './assets/images/game/avatars/vulpix.png',
        imageFace: './assets/images/game/avatars/face/vulpix.png',
        imageCentered: './assets/images/game/avatars/centered/vulpix.png',
        frontGif: './assets/images/game/avatars-gifs/vulpix.gif',
        backGif: './assets/images/game/avatars-gifs/vulpix-back.gif',
    },
    [Avatar.Avatar8]: {
        name: 'Évoli',
        image: './assets/images/game/avatars/eevee.png',
        imageFace: './assets/images/game/avatars/face/eevee.png',
        imageCentered: './assets/images/game/avatars/centered/eevee.png',
        frontGif: './assets/images/game/avatars-gifs/eevee.gif',
        backGif: './assets/images/game/avatars-gifs/eevee-back.gif',
    },
    [Avatar.Avatar9]: {
        name: 'Osselait',
        image: './assets/images/game/avatars/cubone.png',
        imageFace: './assets/images/game/avatars/face/cubone.png',
        imageCentered: './assets/images/game/avatars/centered/cubone.png',
        frontGif: './assets/images/game/avatars-gifs/cubone.gif',
        backGif: './assets/images/game/avatars-gifs/cubone-back.gif',
    },
    [Avatar.Avatar10]: {
        name: 'Magicarpe',
        image: './assets/images/game/avatars/magikarp.png',
        imageFace: './assets/images/game/avatars/face/magikarp.png',
        imageCentered: './assets/images/game/avatars/centered/magikarp.png',
        frontGif: './assets/images/game/avatars-gifs/magikarp.gif',
        backGif: './assets/images/game/avatars-gifs/magikarp-back.gif',
    },
    [Avatar.Avatar11]: {
        name: 'Draco',
        image: './assets/images/game/avatars/dragonair.png',
        imageFace: './assets/images/game/avatars/face/dragonair.png',
        imageCentered: './assets/images/game/avatars/centered/dragonair.png',
        frontGif: './assets/images/game/avatars-gifs/dragonair.gif',
        backGif: './assets/images/game/avatars-gifs/dragonair-back.gif',
    },
    [Avatar.Avatar12]: {
        name: 'Mew',
        image: './assets/images/game/avatars/mew.png',
        imageFace: './assets/images/game/avatars/face/mew.png',
        imageCentered: './assets/images/game/avatars/centered/mew.png',
        frontGif: './assets/images/game/avatars-gifs/mew.gif',
        backGif: './assets/images/game/avatars-gifs/mew-back.gif',
    },
    [Avatar.Avatar1Shiny]: {
        name: 'Bulbizarre',
        image: './assets/images/game/avatars/centered/shiny/bulbasaur-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/bulbasaur-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/bulbasaur-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/bulbasaur-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/bulbasaur-shiny-back.gif',
    },
    [Avatar.Avatar2Shiny]: {
        name: 'Carapuce',
        image: './assets/images/game/avatars/centered/shiny/squirtle-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/squirtle-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/squirtle-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/squirtle-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/squirtle-shiny-back.gif',
    },
    [Avatar.Avatar3Shiny]: {
        name: 'Salamèche',
        image: './assets/images/game/avatars/centered/shiny/charmander-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/charmander-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/charmander-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/charmander-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/charmander-shiny-back.gif',
    },
    [Avatar.Avatar4Shiny]: {
        name: 'Pikachu',
        image: './assets/images/game/avatars/centered/shiny/pikachu-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/pikachu-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/pikachu-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/pikachu-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/pikachu-shiny-back.gif',
    },
    [Avatar.Avatar5Shiny]: {
        name: 'Rondoudou',
        image: './assets/images/game/avatars/centered/shiny/jigglypuff-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/jigglypuff-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/jigglypuff-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/jigglypuff-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/jigglypuff-shiny-back.gif',
    },
    [Avatar.Avatar6Shiny]: {
        name: 'Psykokwak',
        image: './assets/images/game/avatars/centered/shiny/psyduck-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/psyduck-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/psyduck-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/psyduck-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/psyduck-shiny-back.gif',
    },
    [Avatar.Avatar7Shiny]: {
        name: 'Goupix',
        image: './assets/images/game/avatars/centered/shiny/vulpix-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/vulpix-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/vulpix-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/vulpix-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/vulpix-shiny-back.gif',
    },
    [Avatar.Avatar8Shiny]: {
        name: 'Évoli',
        image: './assets/images/game/avatars/centered/shiny/eevee-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/eevee-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/eevee-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/eevee-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/eevee-shiny-back.gif',
    },
    [Avatar.Avatar9Shiny]: {
        name: 'Osselait',
        image: './assets/images/game/avatars/centered/shiny/cubone-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/cubone-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/cubone-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/cubone-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/cubone-shiny-back.gif',
    },
    [Avatar.Avatar10Shiny]: {
        name: 'Magicarpe',
        image: './assets/images/game/avatars/centered/shiny/magikarp-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/magikarp-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/magikarp-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/magikarp-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/magikarp-shiny-back.gif',
    },
    [Avatar.Avatar11Shiny]: {
        name: 'Draco',
        image: './assets/images/game/avatars/centered/shiny/dragonair-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/dragonair-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/dragonair-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/dragonair-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/dragonair-shiny-back.gif',
    },
    [Avatar.Avatar12Shiny]: {
        name: 'Mew',
        image: './assets/images/game/avatars/centered/shiny/mew-shiny.png',
        imageFace: './assets/images/game/avatars/face/shiny/mew-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/shiny/mew-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/shiny/mew-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/shiny/mew-shiny-back.gif',
    },
    [Avatar.Avatar1Evolved]: {
        name: 'Florizarre',
        image: './assets/images/game/avatars/centered/evolved/venusaur.png',
        imageFace: './assets/images/game/avatars/face/evolved/venusaur.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/venusaur.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/venusaur.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/venusaur-back.gif',
    },
    [Avatar.Avatar2Evolved]: {
        name: 'Tortank',
        image: './assets/images/game/avatars/centered/evolved/blastoise.png',
        imageFace: './assets/images/game/avatars/face/evolved/blastoise.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/blastoise.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/blastoise.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/blastoise-back.gif',
    },
    [Avatar.Avatar3Evolved]: {
        name: 'Dracaufeu',
        image: './assets/images/game/avatars/centered/evolved/charizard.png',
        imageFace: './assets/images/game/avatars/face/evolved/charizard.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/charizard.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/charizard.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/charizard-back.gif',
    },
    [Avatar.Avatar4Evolved]: {
        name: 'Raichu',
        image: './assets/images/game/avatars/centered/evolved/raichu.png',
        imageFace: './assets/images/game/avatars/face/evolved/raichu.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/raichu.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/raichu.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/raichu-back.gif',
    },
    [Avatar.Avatar5Evolved]: {
        name: 'Grodoudou',
        image: './assets/images/game/avatars/centered/evolved/wigglytuff.png',
        imageFace: './assets/images/game/avatars/face/evolved/wigglytuff.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/wigglytuff.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/wigglytuff.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/wigglytuff-back.gif',
    },
    [Avatar.Avatar6Evolved]: {
        name: 'Akwakwak',
        image: './assets/images/game/avatars/centered/evolved/golduck.png',
        imageFace: './assets/images/game/avatars/face/evolved/golduck.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/golduck.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/golduck.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/golduck-back.gif',
    },
    [Avatar.Avatar7Evolved]: {
        name: 'Feunard',
        image: './assets/images/game/avatars/centered/evolved/ninetales.png',
        imageFace: './assets/images/game/avatars/face/evolved/ninetales.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/ninetales.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/ninetales.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/ninetales-back.gif',
    },
    [Avatar.Avatar8Evolved]: {
        name: 'Pyroli',
        image: './assets/images/game/avatars/centered/evolved/flareon.png',
        imageFace: './assets/images/game/avatars/face/evolved/flareon.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/flareon.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/flareon.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/flareon-back.gif',
    },
    [Avatar.Avatar9Evolved]: {
        name: 'Ossatueur',
        image: './assets/images/game/avatars/centered/evolved/marowak.png',
        imageFace: './assets/images/game/avatars/face/evolved/marowak.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/marowak.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/marowak.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/marowak-back.gif',
    },
    [Avatar.Avatar10Evolved]: {
        name: 'Léviator',
        image: './assets/images/game/avatars/centered/evolved/gyarados.png',
        imageFace: './assets/images/game/avatars/face/evolved/gyarados.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/gyarados.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/gyarados.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/gyarados-back.gif',
    },
    [Avatar.Avatar11Evolved]: {
        name: 'Dracolosse',
        image: './assets/images/game/avatars/centered/evolved/dragonite.png',
        imageFace: './assets/images/game/avatars/face/evolved/dragonite.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/dragonite.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/dragonite.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/dragonite-back.gif',
    },
    [Avatar.Avatar12Evolved]: {
        name: 'Mewtwo',
        image: './assets/images/game/avatars/centered/evolved/mewtwo.png',
        imageFace: './assets/images/game/avatars/face/evolved/mewtwo.png',
        imageCentered: './assets/images/game/avatars/centered/evolved/mewtwo.png',
        frontGif: './assets/images/game/avatars-gifs/evolved/mewtwo.gif',
        backGif: './assets/images/game/avatars-gifs/evolved/mewtwo-back.gif',
    },
    [Avatar.Avatar1EvolvedShiny]: {
        name: 'Florizarre',
        image: './assets/images/game/avatars/centered/evolved-shiny/venusaur-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/venusaur-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/venusaur-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/venusaur-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/venusaur-shiny-back.gif',
    },
    [Avatar.Avatar2EvolvedShiny]: {
        name: 'Tortank',
        image: './assets/images/game/avatars/centered/evolved-shiny/blastoise-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/blastoise-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/blastoise-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/blastoise-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/blastoise-shiny-back.gif',
    },
    [Avatar.Avatar3EvolvedShiny]: {
        name: 'Dracaufeu',
        image: './assets/images/game/avatars/centered/evolved-shiny/charizard-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/charizard-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/charizard-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/charizard-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/charizard-shiny-back.gif',
    },
    [Avatar.Avatar4EvolvedShiny]: {
        name: 'Raichu',
        image: './assets/images/game/avatars/centered/evolved-shiny/raichu-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/raichu-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/raichu-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/raichu-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/raichu-shiny-back.gif',
    },
    [Avatar.Avatar5EvolvedShiny]: {
        name: 'Grodoudou',
        image: './assets/images/game/avatars/centered/evolved-shiny/wigglytuff-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/wigglytuff-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/wigglytuff-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/wigglytuff-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/wigglytuff-shiny-back.gif',
    },
    [Avatar.Avatar6EvolvedShiny]: {
        name: 'Akwakwak',
        image: './assets/images/game/avatars/centered/evolved-shiny/golduck-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/golduck-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/golduck-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/golduck-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/golduck-shiny-back.gif',
    },
    [Avatar.Avatar7EvolvedShiny]: {
        name: 'Feunard',
        image: './assets/images/game/avatars/centered/evolved-shiny/ninetales-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/ninetales-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/ninetales-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/ninetales-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/ninetales-shiny-back.gif',
    },
    [Avatar.Avatar8EvolvedShiny]: {
        name: 'Pyroli',
        image: './assets/images/game/avatars/centered/evolved-shiny/flareon-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/flareon-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/flareon-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/flareon-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/flareon-shiny-back.gif',
    },
    [Avatar.Avatar9EvolvedShiny]: {
        name: 'Ossatueur',
        image: './assets/images/game/avatars/centered/evolved-shiny/marowak-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/marowak-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/marowak-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/marowak-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/marowak-shiny-back.gif',
    },
    [Avatar.Avatar10EvolvedShiny]: {
        name: 'Léviator',
        image: './assets/images/game/avatars/centered/evolved-shiny/gyarados-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/gyarados-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/gyarados-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/gyarados-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/gyarados-shiny-back.gif',
    },
    [Avatar.Avatar11EvolvedShiny]: {
        name: 'Dracolosse',
        image: './assets/images/game/avatars/centered/evolved-shiny/dragonite-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/dragonite-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/dragonite-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/dragonite-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/dragonite-shiny-back.gif',
    },
    [Avatar.Avatar12EvolvedShiny]: {
        name: 'Mewtwo',
        image: './assets/images/game/avatars/centered/evolved-shiny/mewtwo-shiny.png',
        imageFace: './assets/images/game/avatars/face/evolved-shiny/mewtwo-shiny.png',
        imageCentered: './assets/images/game/avatars/centered/evolved-shiny/mewtwo-shiny.png',
        frontGif: './assets/images/game/avatars-gifs/evolved-shiny/mewtwo-shiny.gif',
        backGif: './assets/images/game/avatars-gifs/evolved-shiny/mewtwo-shiny-back.gif',
    },
    [Avatar.MissingNo]: {
        name: 'MissingNo',
        image: './assets/images/game/avatars/default.png',
        imageFace: './assets/images/game/avatars/face/default.png',
        imageCentered: './assets/images/game/avatars/centered/default.png',
        frontGif: './assets/images/game/avatars-gifs/missingno.gif',
        backGif: './assets/images/game/avatars-gifs/missingno.gif',
    },
};
